const data = [
  {
    name: "Global Automobile Shop",
    id: "1",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 1.55,
    payment: "Cash",
    rating: 4.5,
    votes: 485,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/jaipur/l8/0141px141.x141.200827174203.u6l8/catalogue/the-spare-mart-vaishali-nagar-jaipur-tyre-dealers-1uawkkaekd.jpg?clr=",
  },
  {
    name: "Continental Services",
    id: "2",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 4.51,
    payment: "Online",
    rating: 4.5,
    votes: 854,
    discount: "No",
    image:
      "https://content.jdmagicbox.com/comp/jaipur/21/0141p141std49621/catalogue/the-tyre-zone-jaipur-cirl3.jpg?clr=",
  },
  {
    name: "Hot Wheelz Station",
    id: "3",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 2.35,
    payment: "Cash",
    rating: 5,
    votes: 748,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/hubli/q7/0836px836.x836.171025145541.t1q7/catalogue/hot-wheelz-sirur-park-hubli-car-tyre-dealers-rz3sn.jpg",
  },
  {
    name: "The Good Service",
    id: "4",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 3.0,
    payment: "Online",
    rating: 4.5,
    votes: 651,
    discount: "No",
    image:
      "https://content3.jdmagicbox.com/comp/noida/n6/011pxx11.xx11.160718172929.z5n6/catalogue/salim-tyre-puncher-shop-noida-sector-41-noida-second-hand-tyre-dealers-009s65fryl.jpg",
  },

  {
    name: "Kings of Automobile",
    id: "5",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 4.0,
    payment: "Cash",
    rating: 2.3,
    votes: 665,
    discount: "No",
    image:
      "https://thumbs.dreamstime.com/b/indian-man-sitting-outside-repair-shop-jamnagar-gujarat-india-december-idling-roadside-tyre-puncture-streets-city-204635550.jpg",
  },
  {
    name: "Faruk's Service Station",
    id: "6",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 5.1,
    payment: "Online",
    rating: 3.7,
    votes: 561,
    discount: "Yes",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9YfZ2dZyREay2VYEEVZ_vSKYlm-XJm6aRPA&usqp=CAU",
  },
  {
    name: "Sindh Service Center",
    id: "7",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 2.22,
    payment: "Cash",
    rating: 4.1,
    votes: 651,
    discount: "No",
    image:
      "https://content.jdmagicbox.com/comp/madurai/l6/0452px452.x452.170603132706.q5l6/catalogue/b-kannan-puncture-shop-madurai-isptn89n5w.jpg?clr=",
  },
  {
    name: "Service Wala's",
    id: "8",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 6.6,
    payment: "Online",
    rating: 3.7,
    votes: 445,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/erode/e2/9999px424.x424.191216160634.d3e2/catalogue/sai-swastik-mobile-puncher-erode-ysapipxhsk.jpg?clr=",
  },
  {
    name: "Lords Of Vehicles",
    id: "9",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 1.32,
    payment: "Cash",
    rating: 2.9,
    votes: 64,
    discount: "No",
    image:
      "https://content3.jdmagicbox.com/comp/madurai/s6/0452px452.x452.190313094550.i4s6/catalogue/hms-puncture-shop-madurai-vcdwgqaf4k.jpg?clr=1a4d4d",
  },

  {
    name: "Mr.Automobile",
    id: "10",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 1.11,
    payment: "Online",
    rating: 4.9,
    votes: 963,
    discount: "No",
    image:
      "https://content.jdmagicbox.com/comp/junagadh/m5/9999px285.x285.130914101629.w3m5/catalogue/universal-engineering-co-jayshree-tokies-road-junagadh-tyre-dealers-mrf-mkvkx7d.jpg",
  },
  {
    name: "Rayjay Service Shop",
    id: "11",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 3.75,
    payment: "Cash",
    rating: 5.0,
    votes: 396,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/erode/t9/9999px424.x424.181222111932.l2t9/catalogue/jp-mobile-puncture-shop-erode-qca0sivcry.jpg",
  },
  {
    name: "Punjabi Bhai Shop",
    id: "12",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 4.44,
    payment: "Online",
    rating: 2.9,
    votes: 131,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/nashik/p2/0253px253.x253.140508144645.h5p2/catalogue/highway-tyre-house-nashik-road-nashik-tyre-dealers-uybpadi02r.jpg?clr=",
  },
  {
    name: "Yuvi's Service Center",
    id: "13",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 3.21,
    payment: "Cash",
    rating: 4.5,
    votes: 123,
    discount: "No",
    image:
      "https://content.jdmagicbox.com/comp/jaipur/l8/0141px141.x141.200827174203.u6l8/catalogue/the-spare-mart-vaishali-nagar-jaipur-tyre-dealers-1uawkkaekd.jpg?clr=",
  },
  {
    name: "Navrat Service Shop",
    id: "14",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 6.54,
    payment: "Online",
    rating: 3.1,
    votes: 987,
    discount: "No",
    image:
      "https://content.jdmagicbox.com/comp/hubli/q7/0836px836.x836.171025145541.t1q7/catalogue/hot-wheelz-sirur-park-hubli-car-tyre-dealers-rz3sn.jpg",
  },
  {
    name: "Baba ki Dukaan",
    id: "15",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 7.41,
    payment: "Cash",
    rating: 4.1,
    votes: 147,
    discount: "No",
    image:
      "https://lh5.googleusercontent.com/p/AF1QipMO4Vks8r7DtRlRSwr5rEUF6wP688eQwMTJnHH2=w1080-k-no",
  },
  {
    name: "Dada ki Dukaan",
    id: "16",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 3.65,
    payment: "Online",
    rating: 3.7,
    votes: 134,
    discount: "Yes",
    image:
      "https://lh5.googleusercontent.com/p/AF1QipMO4Vks8r7DtRlRSwr5rEUF6wP688eQwMTJnHH2=w1080-k-no",
  },
  {
    name: "Rohit Service Center",
    id: "17",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 1.65,
    payment: "Cash",
    rating: 5.0,
    votes: 564,
    discount: "Yes",
    image:
      "https://lh5.googleusercontent.com/p/AF1QipMO4Vks8r7DtRlRSwr5rEUF6wP688eQwMTJnHH2=w1080-k-no",
  },
  {
    name: "Bhuvan's Automobile Center",
    id: "18",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 2.0,
    payment: "Online",
    rating: 4.8,
    votes: 65,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/nashik/p2/0253px253.x253.140508144645.h5p2/catalogue/highway-tyre-house-nashik-road-nashik-tyre-dealers-uybpadi02r.jpg?clr=",
  },
  {
    name: "Nana's Service",
    id: "19",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 3.38,
    payment: "Cash",
    rating: 3.8,
    votes: 883,
    discount: "No",
    image:
      "https://lh5.googleusercontent.com/p/AF1QipMO4Vks8r7DtRlRSwr5rEUF6wP688eQwMTJnHH2=w1080-k-no",
  },
  {
    name: "Chandak Automobiles",
    id: "20",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 4.56,
    payment: "Online",
    rating: 4.9,
    votes: 51,
    discount: "Yes",
    image:
      "https://lh5.googleusercontent.com/p/AF1QipMO4Vks8r7DtRlRSwr5rEUF6wP688eQwMTJnHH2=w1080-k-no",
  },
  {
    name: "Murli Service Center",
    id: "21",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 8.54,
    payment: "Cash",
    rating: 2.5,
    votes: 841,
    discount: "No",
    image:
      "https://lh5.googleusercontent.com/p/AF1QipMO4Vks8r7DtRlRSwr5rEUF6wP688eQwMTJnHH2=w1080-k-no",
  },
  {
    name: "Old is gold center",
    id: "22",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 3.11,
    payment: "Online",
    rating: 4.9,
    votes: 615,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/nashik/p2/0253px253.x253.140508144645.h5p2/catalogue/highway-tyre-house-nashik-road-nashik-tyre-dealers-uybpadi02r.jpg?clr=",
  },
  {
    name: "Firangi Service Shop",
    id: "23",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 3.24,
    payment: "Cash",
    rating: 3.6,
    votes: 614,
    discount: "No",
    image:
      "https://content.jdmagicbox.com/comp/junagadh/m5/9999px285.x285.130914101629.w3m5/catalogue/universal-engineering-co-jayshree-tokies-road-junagadh-tyre-dealers-mrf-mkvkx7d.jpg",
  },
  {
    name: "Manor Automobiles",
    id: "24",
    services: [
      "Puncture",
      "Wash",
      "Full Service",
      "Part Replacement",
      "Oil change",
      "Paint",
      "Other",
    ],
    radius: 1.11,
    payment: "Online",
    rating: 2.5,
    votes: 854,
    discount: "Yes",
    image:
      "https://content.jdmagicbox.com/comp/nashik/p2/0253px253.x253.140508144645.h5p2/catalogue/highway-tyre-house-nashik-road-nashik-tyre-dealers-uybpadi02r.jpg?clr=",
  },
];

export default data;
